### ISSUE TITLE
Add a progress bar for computational heavy functions

### ISSUE THREAD

**Issue by hyzhou1990** [wuaipinglab/sitePath#20]
sitePath is designed for processing both small and large scale data. During my testings, small data with less than 500 sequences could be completed in 1min, which is very great. However, when I processed some large data with more than 6,000 sequences. Hours should be taken for analysis. I can't get the rate of the progress in any place, neither can i know how much time left before the complete of the analysis. So, I suggest to add a progress bar for reference. It could be seen like this:
"""
Your data is too large, and should take more time for analysis than common. You can track the progress below:
[=====> 12%                                                                                  ]
"""

**Comment by jichengyang202301** [comment]
The execution of `lineagePath`, `sitesMinEntropy` , `fixationSites` and `parallelSites` fuctions will be featured with progress bar.

**Comment by jichengyang202301** [comment]
When using multiprocessing, progress bar is too difficult to be implemented and maintained. So though very disappointing, this feature request is declined
